apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-topic-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-topic-operator
  template:
    metadata:
      labels:
        name: strimzi-topic-operator
    spec:
      serviceAccountName: strimzi-topic-operator
      containers:
        - name: strimzi-topic-operator
          # image: registry.redhat.io/amq7/amq-streams-rhel8-operator:2.1.0
          # image: localhost:5000/amq-streams-rhel8-operator:2.1.0
          image: quay.io/strimzi/operator:0.28.0
          args:
          - /opt/strimzi/bin/topic_operator_run.sh
          env:
            - name: STRIMZI_RESOURCE_LABELS
              value: "strimzi.io/cluster=my-cluster"
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: host.minikube.internal:9094
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: host.minikube.internal:2181
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "18000"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS
              value: "6"
            - name: STRIMZI_USE_ZOOKEEPER_TOPIC_STORE
              value: "true"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_PUBLIC_CA
              value: "true"
            - name: STRIMZI_TLS_AUTH_ENABLED
              value: "false"
            - name: STRIMZI_TLS_ENABLED
              value: "false"
            - name: STRIMZI_SASL_ENABLED
              value: "false"
            - name: STRIMZI_SECURITY_PROTOCOL
              value: SSL
            - name: STRIMZI_TRUSTSTORE_LOCATION
              value: "/etc/mtls-admin-certs/truststore.p12"
            - name: STRIMZI_TRUSTSTORE_PASSWORD
              value: "123456"
            - name: STRIMZI_KEYSTORE_LOCATION
              value: "/etc/mtls-admin-certs/keystore.p12"
            - name: STRIMZI_KEYSTORE_PASSWORD
              value: "123456"
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: my-cluster-admin-certs
              mountPath: /etc/mtls-admin-certs/
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 500m
      volumes:
        - name: my-cluster-admin-certs
          configMap:
            name: my-cluster-admin-certs
            defaultMode: 420
  strategy:
    type: Recreate
